# .github/workflows/actions_gcm_check.yml
name: Test GCD Script

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Permission
        run: chmod +x cal_gcm cal_gcm_check
      - name: Test run
        run: ./cal_gcm_check
